### ISSUE TITLE
Game Crashing when powering water wheel with Aqueduct Water

### ISSUE THREAD

**Issue by lightlike** [DaedalusGame/BetterWithAddons#101]
Forge: 14.23.2.2651
BWM: 2.1.5
BWA: 0.37

World is corrupted after crash.

Exception:

> Description: Ticking block entity
> 
> java.lang.ClassCastException: betterwithaddons.block.BlockAqueductWater cannot be cast to net.minecraft.block.BlockLiquid
> 	at betterwithmods.api.block.IWaterCurrent.lambda$fromLiquid$1(IWaterCurrent.java:20)
> 	at betterwithmods.common.blocks.mechanical.tile.TileEntityWaterwheel.calculatePower(TileEntityWaterwheel.java:154)
> 	at streams.tileentity.package$.calculatePower(package.scala:29)
> 	at streams.tileentity.package.calculatePower(package.scala)
> 	at betterwithmods.common.blocks.mechanical.tile.TileAxleGenerator.func_73660_a(TileAxleGenerator.java:76)
> 	at net.minecraft.world.World.func_72939_s(World.java:1832)
> 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
> 	at java.lang.Thread.run(Unknown Source)

**Comment by DaedalusGame** [comment]
aw man
i made a fix for this in BWM, see if [this build](https://ci.blamejared.com/job/BetterWithMods/455/) (when it's done) works for you

**Comment by lightlike** [comment]
Works fine in the new build.
Thanks.
