### ISSUE TITLE
Can't find any Mulberry Tree and no options for that...

### ISSUE THREAD

**Issue by Fireztonez** [DaedalusGame/BetterWithAddons#103]
Hello,
I currently develop a modpack, like you probably already know! And I look in creative, and try to find a Mulberry Tree, and I look on over 7000 block... I don't how many is supposed to generate, but for sure, this is realy hard to find now!!

Can you add an option for turn up or down the spawn rate of Mulberry Tree??

Fireztonez

**Comment by Fireztonez** [comment]
I just see, the mulberry tree sapling have a crafting recipe with the infuser, so, does that mean they do not spawn naturally in the world?

**Comment by DaedalusGame** [comment]
they don't spawn naturally, no
Sevtech adds natural spawns using Recurrent Complex

**Comment by Fireztonez** [comment]
Oki, that's why I can't find it!!

Thank's I will do the same thing I think, becose I will need Mulberry for somes recipes and, Mulberry Stick for make a Bow...

Thank's for that fast reply!!
