### ISSUE TITLE
Crash on launch in dev environment.

### ISSUE THREAD

**Issue by temp1011** [DaedalusGame/BetterWithAddons#105]
https://gist.github.com/temp1011/5e8c9edddd214bbebf7d3eae0ca2c8a2. I'm not really sure what the problem is, other mods seem to work fine when dropped into run/mods. Maybe something to do with reflection somewhere?

**Comment by DaedalusGame** [comment]
uhm i'm not sure how to help with this
the line in question is `this.setDefaultState(this.blockState.getBaseState().withProperty(AGE, Integer.valueOf(0)));`
the offending field is Block::blockState
but this happens after running a constructor from another class which also accesses blockState
`this.setDefaultState(this.blockState.getBaseState().withProperty(NORTH, EnumAttachPosition.NONE).withProperty(EAST, EnumAttachPosition.NONE).withProperty(SOUTH, EnumAttachPosition.NONE).withProperty(WEST, EnumAttachPosition.NONE).withProperty(BlockRedstoneWire.POWER, Integer.valueOf(0)));`

The only thing I can do is replace those calls to this.blockState with getDefaultState instead and see if that helps. This is probably a mapping mismatch but I'm not sure why the mapping exists in one method and not another...

**Comment by temp1011** [comment]
Huh, weird. Don't worry too much about it. Maybe it's something modifying things at the bytecode level?

**Comment by DaedalusGame** [comment]
hm what mapping version are you using on that note?

**Comment by temp1011** [comment]
20171003

**Comment by DaedalusGame** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/4852
I replaced the field reference for now if you want a build with that

**Comment by temp1011** [comment]
Thanks!

**Comment by DaedalusGame** [comment]
resolved a while ago i think
