### ISSUE TITLE
Crash after updating to build 0.39 (1.12)

### ISSUE THREAD

**Issue by ate0ate** [DaedalusGame/BetterWithAddons#109]
I believe the Better with Wheat portion of the mod is having an issue after updating to the latest .39 hotfix, as I now get this crash at startup...
https://pastebin.com/6n2HDARG
 I usually play with the Better with Wheat module enabled with these settings...
https://pastebin.com/xss9Q5tC
Disabling the module does indeed prevent the crash. Please let me know if you need any further info. Thanks!

**Comment by DaedalusGame** [comment]
Should be fixed in hotfix2
