### ISSUE TITLE
HardcoreShearing causes Mooshrooms to drop 10 mushrooms and convert into 2 cows.

### ISSUE THREAD

**Issue by Jandakast** [DaedalusGame/BetterWithAddons#110]
With Hardcore Shearing enabled if you shear a Mooshroom it will drop 10 mushrooms and convert/spawn 2 cows. This was originally reported on the SevTech issue tracker but can reproduced with just Better with Mods and Better with Addons running. 

https://github.com/Darkosto/SevTech-Ages/issues/2036

Here are the configs in case this is a weird interaction caused by specific config options. 

https://gist.github.com/Jandakast/1d077933da2f70bdac7edf5ef18c6d2d
https://gist.github.com/Jandakast/5a34700b6657e900c9a8feb7a208953c

Better With Addons-0.39hotfix2
BetterWithMods-1.12-2.1.12
Forge 2669

**Comment by artdude543** [comment]
Any chance we could have this pushed to CF @DaedalusGame ❤️
