### ISSUE TITLE
Egg Incubation appears to ghost load load chunks

### ISSUE THREAD

**Issue by thiakil** [DaedalusGame/BetterWithAddons#122]
![eggs](https://user-images.githubusercontent.com/1788847/41294607-0681b2fa-6e8b-11e8-8c78-7fde3db3def4.png)

Seems its possible to have item entities in the tracked list that were unloaded. You might want to listen for a chunk unload event, and also potentially check the entity's position is loaded.

Better With Addons-0.40hotfix

**Comment by thiakil** [comment]
Actually, that seems to be _generating_ the chunk. I have no idea how that would happen.

**Comment by DaedalusGame** [comment]
oof what
actually no it just loads the chunk, that func_180514_a is the method that recreates structures, i will fix this later today

**Comment by thiakil** [comment]
No idea, but either way, youve got an entity in an unloaded chunk there :P

**Comment by DaedalusGame** [comment]
fixed (finally)
