### ISSUE TITLE
[1.12] Crash on Gamestart

### ISSUE THREAD

**Issue by MasterEnderman** [DaedalusGame/BetterWithAddons#125]
Forge: 2707
Better With Mods: 2.1.24-686 (jenkins)
Better With Addons: 0.41hotfix
Crash: https://paste.dimdev.org/hirocobucu.mccrash

**Comment by Charnuz** [comment]
This happens with the latest version of BWM

**Comment by angelnc1989** [comment]
I'm getting the same crash, but only after heavily tweaking the config file.

**Comment by LocalBoomer** [comment]
Same issue, more (probably useless) information: https://pastebin.com/RvbAqpZa

MC 1.12.2
Forge 14.23.4.2727
BWM 2.2.02
BWA 0.41hotfix
