### ISSUE TITLE
Tea Plants cause game to crash

### ISSUE THREAD

**Issue by avatarofmadness42** [DaedalusGame/BetterWithAddons#127]
When using the 0.41 Hotfix version of BetterWithAddons, attempting to harvest the tea plant causes the game to crash. I suspect this might be an incompatibility with the Simple Harvest mod, as all other crops I tried worked perfectly with that mod. I've tried it three times today, and all three times the game has crashed. The logs are provided. A full list of the mods I'm using can also be provided if need be.
[crash-2018-07-07_18.10.21-client.txt](https://github.com/DaedalusGame/BetterWithAddons/files/2172585/crash-2018-07-07_18.10.21-client.txt)
[crash-2018-07-07_18.16.24-client.txt](https://github.com/DaedalusGame/BetterWithAddons/files/2172586/crash-2018-07-07_18.16.24-client.txt)
[crash-2018-07-07_18.23.31-client.txt](https://github.com/DaedalusGame/BetterWithAddons/files/2172587/crash-2018-07-07_18.23.31-client.txt)

**Comment by DaedalusGame** [comment]
use a different rightclick harvesting mod instead, the mod you're using checks directly for the age property, which is always gonna be different if the crop has more or less than 7 stages.
ironically you can try [this one](https://minecraft.curseforge.com/projects/simpleharvest) and complain to curse that they allowed two projects with the exact same slug :p
