### ISSUE TITLE
Version 0.42 Causes Crash When Loading

### ISSUE THREAD

**Issue by avatarofmadness42** [DaedalusGame/BetterWithAddons#128]
Sorry, it's me again. I made the switch to version 0.42 of Better With Addons, but it seems to be causing my game to crash on loading. I've again attached the crash report, but I can't think of anything that is causing this behavior off the top of my head.
[crash-2018-07-09_18.04.09-client.txt](https://github.com/DaedalusGame/BetterWithAddons/files/2175213/crash-2018-07-09_18.04.09-client.txt)
I'll continue using the 0.41Hotfix version for now, but I felt I should let you know anyway.

**Comment by DaedalusGame** [comment]
update BWM
