### ISSUE TITLE
wool armor recipe broken as fuck

### ISSUE THREAD

**Issue by primetoxinz** [DaedalusGame/BetterWithAddons#129]
and if you put fleece into a crafting table, close the gui it will both drop the entity and put it into your inventory. Cannot reproduce this with other items.

**Comment by DaedalusGame** [comment]
literally just your recipe but with fleece

**Comment by primetoxinz** [comment]
:thinking: ok, but the wool version doesn't do this

**Comment by DaedalusGame** [comment]
can't reproduce
