### ISSUE TITLE
You are replacing %VERSION% but you are using @VERSION@

### ISSUE THREAD

**Issue by Rikshy** [DaedalusGame/BetterWithAddons#145]
Nothing major, but i saw it while browsing your code :P

https://github.com/DaedalusGame/BetterWithAddons/blob/2795d85795e732dce2d170c10d120702767e3415/build.gradle#L29

https://github.com/DaedalusGame/BetterWithAddons/blob/2795d85795e732dce2d170c10d120702767e3415/src/main/java/betterwithaddons/lib/Reference.java#L7

**Comment by DaedalusGame** [comment]
oops this is probably the third or fourth issue about it
