### ISSUE TITLE
Possible scaffold block issue

### ISSUE THREAD

**Issue by vivagabe** [DaedalusGame/BetterWithAddons#148]
Scaffold blocks will not allow you to place additional scaffold blocks on either of its sides.  Is this working as intended?

**Comment by DaedalusGame** [comment]
Does shift-rightclick not work?

**Comment by vivagabe** [comment]
No, shift-rightclick doesn't work.

**Comment by DaedalusGame** [comment]
I'll take a look then

**Comment by DaedalusGame** [comment]
oh I think I know what this means finally
you're trying to place a scaffold in midair next to another block
scaffolds need a solid block (or another scaffold) underneath as support, so this is intentional. you can make horizontal bridges with rope

(2 months woo)
