### ISSUE TITLE
Crash in Sevtech 3.0.8 when adding Additional Pipes mod

### ISSUE THREAD

**Issue by ReportBot9009** [DaedalusGame/BetterWithAddons#149]
Hello,
I installed the Additional Pipes mod and am getting this strange crash. I reported it to Additional Pipes dev and they said report it over to you guys.

Here is the report on their git: https://github.com/tcooc/AdditionalPipesBC/issues/183

Here are the crashes
MultiMC Log: https://paste.ee/p/b0AhS
Crash Report File: https://paste.ee/p/QZCGr

I am running Sevtech 3.0.8
Forge 14.23.4.2765

I've added Optifine and Seus Renew

Thanks for the help

**Comment by ReportBot9009** [comment]
I just downloaded the 0.46 from Curse and popped it in my MultiMC mods folder. I loaded it up and it crashed during the load process: https://paste.ee/p/Ozp8W

**Comment by DaedalusGame** [comment]
your 0.46 crash happens because you haven't updated BWM aswell
the original crash happens because Buildcraft's Facade module gathers facade blocks before I can "finish initialization" on zen garden sand. I'll look into a more robust solution to this.

**Comment by ReportBot9009** [comment]
Shall I post this over at Buildcraft git?

Ah, I knew I was doing something wrong. Let me update BWM and see if that fixes it.

**Comment by ReportBot9009** [comment]
I updated BWM and BWA as well as the latest Buildcraft and the problem still persists. I opened an issue with Buildcraft so they are aware since it is mentioned in the report as well.
Thanks for your help and development :)
