### ISSUE TITLE
Book of Single example pictures broken after installation of BWA

### ISSUE THREAD

**Issue by UristMcStoutHorn** [DaedalusGame/BetterWithAddons#150]
Even the regular BWM example pics of the kiln structures or the crash course manual pics of the windmills end up as dead red links.  Have tried rebooting, but to no avail.  Were showing up just fine before inclusion of BWA into pack.
Using the following versions of the mods:  BetterWithMods-1.12-2.3.16  &  BetterWithLib-1.12-1.5  &  Better+With+Addons-0.46
![oddity](https://user-images.githubusercontent.com/4361068/48102291-622c2780-e1f8-11e8-887f-0a4479a486b6.png)

**Comment by DaedalusGame** [comment]
if this still persists after next release i have officially no idea why it happens
