### ISSUE TITLE
Suggestion: Make Soaking Unit work with any ice blocks

### ISSUE THREAD

**Issue by nick-johnson** [DaedalusGame/BetterWithAddons#151]
Current Cherrywood Soaking Unit only works with a piece of vanilla Ice above it, and does not allow for other ice variants like vanilla Packed Ice, NetherEx Frostburn Ice, Chisel Ice variants. If the Ice is exposed to any light or temperature varying mods like ToughAsNails, the Ice melts and the Soaking Unit no longer works. 

The soaking unit should at least work with Packed Ice, and optionally modded ices.

**Comment by DaedalusGame** [comment]
i disagree, packed ice will be the only ice it won't work with because it's literally not even ice
it's just slippery rock in the code
