### ISSUE TITLE
Resource pack side infuser orb and spirit textures

### ISSUE THREAD

**Issue by Foreck1** [DaedalusGame/BetterWithAddons#165]
Spirit orbs as well as the small pool and orb floating on top of the infuser have a red-only gradient, suggestion to have these resources in the assets folder so resource packs can change their textures/colormap.

**Comment by DaedalusGame** [comment]
https://github.com/DaedalusGame/BetterWithAddons/blob/1.12/src/main/resources/assets/betterwithaddons/textures/entity/infuser.png

**Comment by Foreck1** [comment]
that texture gets a red tint over it as more souls are added, that can't be changed.

**Comment by DaedalusGame** [comment]
it can be since i made the orb colors configurable (i didn't forget that one)

**Comment by Foreck1** [comment]
So it will be available in the next release?

**Comment by DaedalusGame** [comment]
yep
