### ISSUE TITLE
Betweenlands Ring Of Recruitment crashes server with Karate Zombies

### ISSUE THREAD

**Issue by sporefreak** [DaedalusGame/BetterWithAddons#176]
I was using a ring of Recruitment from the between lands, it works fine on almost any mob, but I recruited a karate zombie in the hunting dimension (Not sure if that matters) and I died a bit later, upon using a Corail Tombstones key to teleport back to the grave/death point the server crashed almost immediately, I did right click the tombstone though im not sure if it was before or after the crashing started, the crash logs kept pointing to the karate zombie and upon logging into the server the whole thing would crash again.

**Comment by DaedalusGame** [comment]
need crashlog

**Comment by sporefreak** [comment]
https://pastebin.com/qUhkXxjL
Deleting the hunting dimension fixed the issue.
is it because of the Vehicle being null/error that could cause the problem?
