### ISSUE TITLE
Aqueduct question

### ISSUE THREAD

**Issue by WolfieWaffle** [DaedalusGame/BetterWithAddons#19]
Are aqueducts supposed to allow flowing water, such as from a screw pump after elevated? because if so It does not appear to be working.

**Comment by DaedalusGame** [comment]
For right now, they only take ordinary source blocks, which isn't 100% ideal. I'll look into supporting screwpumps.

**Comment by WolfieWaffle** [comment]
ah ok, no problem

**Comment by DaedalusGame** [comment]
I've allowed screwpump outputs to work as source blocks for the aqueduct. Only the water directly above the screwpump will work.
