### ISSUE TITLE
crash at loading

### ISSUE THREAD

**Issue by Hypsellis** [DaedalusGame/BetterWithAddons#20]
The game crashes at last loading step. I use Better With Mod 1.2.9 and Better With Addons 0.10. https://pastebin.com/7kcAeMqW

**Comment by DaedalusGame** [comment]
interesting, can you confirm that this crash happens with BWM 1.2.19+?

**Comment by DaedalusGame** [comment]
I've added a null check for the case that a tool doesn't have a model, or if some other mod has eaten the list of models. Additionally I've added a config option for turning the toolshard renderer off and toolshards will render as the respective tool model instead of a broken version.

**Comment by Hypsellis** [comment]
I get this crash with the new BWM version. https://pastebin.com/mVSw3Uda

**Comment by DaedalusGame** [comment]
oh there it is, primetoxinz is just too fast, will fix

**Comment by DaedalusGame** [comment]
Hm. I can't reproduce in dev
