### ISSUE TITLE
0.11hotfix crashes dedicated server Forge 1.11.2 build 2366

### ISSUE THREAD

**Issue by kreezxil** [DaedalusGame/BetterWithAddons#22]
Notes:
     on startup with No Such Method Error

crash report:
https://gist.github.com/ba4105c87a0cd8ff7114007645084aad

fml server latest:
https://gist.github.com/1d2315359f88ba5d1f0c08f874e898d9

**Comment by DaedalusGame** [comment]
BWM 1.2.9 is outdated. 0.11 works with BWM 1.2.33, 0.11hotfix works with BWM 1.2.34+

**Comment by kreezxil** [comment]
Heh, I must've been asleep at the wheel, thought I updated bwm on the server when I didn't. :(
