### ISSUE TITLE
better with addons crashes better with mods on 1.11.2

### ISSUE THREAD

**Issue by demonnerd** [DaedalusGame/BetterWithAddons#28]
[crash-2017-07-22_18.32.35-client.txt](https://github.com/DaedalusGame/BetterWithAddons/files/1168131/crash-2017-07-22_18.32.35-client.txt)

**Comment by DaedalusGame** [comment]
Your version is outdated because curse decides to ignore all beta builds, even if the last release build was months ago. Grab BWM 1.2.40

**Comment by demonnerd** [comment]
I did not see that. my apology

**Comment by DaedalusGame** [comment]
no problem :p
