### ISSUE TITLE
Setting a [0,15] property field to 16 crashes game

### ISSUE THREAD

**Issue by asiekierka** [DaedalusGame/BetterWithAddons#41]
http://img.asie.pl/3FBM

No, FoamFix is not at fault here, don't worry

**Comment by DaedalusGame** [comment]
ah yes, maybe block matchers shouldn't output 16 redstone power that would certainly be good

**Comment by asiekierka** [comment]
yes that would be a good idea

clamping the received power to [0, 15] would be a great idea too but you might want to do both.
