### ISSUE TITLE
Crash with latest BwM

### ISSUE THREAD

**Issue by vivagabe** [DaedalusGame/BetterWithAddons#49]
[crash-2017-09-10_20.32.42-client.txt](https://github.com/DaedalusGame/BetterWithAddons/files/1291273/crash-2017-09-10_20.32.42-client.txt)

I get this crash with the latest BwM and BwA.  

EDIT: This is for 1.12.1

**Comment by XvSkItZvX** [comment]
I have also received the same crash with MC 1.12.
