### ISSUE TITLE
Naturally spawned Karate Zombies don't have spirits.

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [DaedalusGame/BetterWithAddons#55]
When Karate Zombies are spawned naturally, [they have 0 spirits](https://vgy.me/kSbsRk.png), but when i spawn them with an egg, [they have their spirits value generated properly](https://vgy.me/UQE938.png).

Steps to reproduce:
1. Create a world.
2. Wait for a Karate Zombie to spawn.
3. Kill it. You can see that no spirits are dropped.

Tested with: BWM 1.12-2.0.14, BWA 0.28, Forge 1.12.2-14.23.0.2491.

**Comment by DaedalusGame** [comment]
what the heck, ok i'll check it out

**Comment by DaedalusGame** [comment]
wait a sec i have this confirmed working for someone else tho

**Comment by DaedalusGame** [comment]
giterdun
