### ISSUE TITLE
Spindle Recipes added by CraftTweaker not showing in JEI

### ISSUE THREAD

**Issue by nmarshall23** [DaedalusGame/BetterWithAddons#56]
Spindle Recipes added by CraftTweaker not showing in JEI. 
They work fine. Just do not show up in JEI.

Here is the zen script code:
```
mods.betterwithaddons.Spindle.add([<harvestcraft:wovencottonitem>],<harvestcraft:cottonitem> * 4,false);
mods.betterwithaddons.Spindle.add([<minecraft:wool>],<harvestcraft:wovencottonitem> * 2,false);
```

I am using the latest versions of BWA, BWM, and CraftTweaker.

**Comment by DaedalusGame** [comment]
interesting, this might be the same issue Soot has, and I haven't figured it out yet. Is the Spindle JEI handler just gone or do only the added recipes not show up? Also can you upload your game log as a paste/gist/whatever so I can check if there's an exception happening at some point during startup?

**Comment by nmarshall23** [comment]
> Is the Spindle JEI handler just gone or do only the added recipes not show up?

The normal Spindle JEI gui page still works, and lists the recipes added by BWA. 

When I get home I will upload a copy of my logs.

**Comment by MasterEnderman** [comment]
Which log do you want? Just asking, because i have the same problem.

**Comment by DaedalusGame** [comment]
on virtue of having refactored everything about this this might be fixed now
