### ISSUE TITLE
Better with Wheat & Villagers

### ISSUE THREAD

**Issue by Ash70** [DaedalusGame/BetterWithAddons#60]
Not sure if this is a bug or intended? But when Better with Wheat is enabled, villagers leave behind empty farmland after harvesting wheat. I don't know if this messes up their bread production also?

**Comment by DaedalusGame** [comment]
Oh, I know why this happens, when Villagers harvest a field, they will obtain only Wheat but no seeds, so they can't replant, I'll look into making a fix for this.
