### ISSUE TITLE
Better with Wheat not working

### ISSUE THREAD

**Issue by Qohelethh** [DaedalusGame/BetterWithAddons#61]
In the latest release, I have Better with Wheat enabled, but the behavior is still default vanilla minecraft behavior. There's no recipe for hay, wheat is still ground into flour, etc.

**Comment by Lordician** [comment]
In the config under the betterwithwheat part of the config put the:
`B:Enabled= true`
This will enable the betterwithwheat part of the mod.
By default this is on false and thus off.

**Comment by Qohelethh** [comment]
As I said, I have all the relevant sections in the config file enabled.

```
    betterwithwheat {
        # Haybales require hay instead of wheat.
        B:ChangeHayBales=true

        # Changes textures of Wheat and Wheat Seeds.
        B:ChangeTextures=true

        # Carrots and Potatoes cannot be instantly harvested, and instead have a breaktime and a preferred tool (hoe)
        B:DigUpCrops=true
        B:Enabled=false

        # Instead of milling wheat into flour, wheat seeds must be milled instead.
        B:MillGrain=true

        # Wheat, when harvested, will drop wheat and hay instead.
        B:ReplaceWheatDrops=true

        # Wheat can be threshed into seeds using shovels.
        B:ThreshWheat=true

        # Wheat can be threshed into seeds using a millstone.
        B:ThreshWheatMill=true
```

**Comment by DaedalusGame** [comment]
B:Enabled=true

**Comment by Qohelethh** [comment]
The one in the carrots and potatoes section?

**Comment by DaedalusGame** [comment]
yes, it's only collapsed like that because it doesn't have a description, I've added a description but not pushed a new version yet unfortunately.

**Comment by Qohelethh** [comment]
Ah, okay. I thought that was for enabling the carrots and potatoes modification. Thanks!

**Comment by Lordician** [comment]
I wasn't very clear i guess, but i am glad you found it now.
I actually ran into the same issue earlier and remembered i used to have to change one config value that was less obvious last time.

**Comment by DaedalusGame** [comment]
this is resolved i think
