### ISSUE TITLE
Greatbows don't fire greatarrows when CoFH Core is installed

### ISSUE THREAD

**Issue by Kevun1** [DaedalusGame/BetterWithAddons#63]
Forge v2545

Bug: 
1. Put some greatarrows in your inventory
2. Try firing greatbow, but it doesn't work

Greatbows do work with regular vanilla arrows though, but since they're much slower to draw but do the same damage with them as the vanilla bow, they're basically useless right now.

EDIT: This bug only occurs when CoFH Core is installed, and I suspect the issue is on their side. [I've created an issue here](https://github.com/CoFH/Feedback/issues/663)

**Comment by DaedalusGame** [comment]
This appears to be fixed on their end now.
