### ISSUE TITLE
[1.12.2] Crash When Joining A World With A Moving Piston

### ISSUE THREAD

**Issue by EmosewaGamer** [DaedalusGame/BetterWithAddons#66]
So this is what happened:
 I connected a vanilla redstone clock circuit to a sticky piston (which had an Iron Rod from Quark attached to it (to break blocks in front of it)) and everything was fine. However, now every time I join that world I get the following crash: 
https://pastebin.com/0yKP4RiL

**Comment by DaedalusGame** [comment]
Oh nice, probably piston TE's with a null world *sigh*
