### ISSUE TITLE
Aqueducts convert any bucket into an iron bucket

### ISSUE THREAD

**Issue by justinrusso** [DaedalusGame/BetterWithAddons#68]
Hello!

I've tried with multiple different modded buckets, and all of them turn into an iron bucket when used on the water in the aqueduct.

Thanks for your work 👍

**Comment by DaedalusGame** [comment]
hey would you believe me that this is a problem with the bucket or some other mod and not with aqueduct water, i only declare aqueduct water to have a liquid amount.

**Comment by justinrusso** [comment]
Its likely because its not *exactly* water. Two of the buckets I cannot even get water from a normal source,

**Comment by DaedalusGame** [comment]
Can you give a list of buckets that transform?

**Comment by justinrusso** [comment]
```
ceramics:clay_bucket
thebetweenlands:syrmorite_bucket
thebetweenlands:weedwood_bucket
```

**Comment by justinrusso** [comment]
I think thats all the buckets we have. I know they don't have an empty version (compared to the way forge/mc does it), which I feel like does cause issues.

**Comment by DaedalusGame** [comment]
can you try opening this up with the mod authors of those buckets or with BWM? I do nothing that even references an iron bucket in the code so this is either a Hardcore Buckets problem (unlikely as it's off in sevtech from what i've seen) or a problem with the buckets themselves.

**Comment by justinrusso** [comment]
Not sure what has changed, but this is working as expected now.

**Comment by DaedalusGame** [comment]
thank god
