### ISSUE TITLE
Unusual Aqueduct behavior if a water source is placed on it

### ISSUE THREAD

**Issue by justinrusso** [DaedalusGame/BetterWithAddons#69]
When a water source is placed, the aqueduct still functions. If the source is removed, the entire aqueduct dries out and then re-fills. Not sure if this can be fixed, but figured I'd at least report it

See https://github.com/Darkosto/SevTech-Ages/issues/346 for more detail with images

**Comment by DaedalusGame** [comment]
This is an artifact of how it works internally. Placing water sources in aqueducts is also a rare usecase, so I don't know if this warrants fixing.

**Comment by justinrusso** [comment]
Had a feeling. In the grand scheme of things, its pretty minor. Figured I'd report anyways and make sure its known at least
