### ISSUE TITLE
[Mod Interaction] Make TCon Kamas give fleece instead of vanilla wool

### ISSUE THREAD

**Issue by justinrusso** [DaedalusGame/BetterWithAddons#75]
Hello,

Would you be able to make it so the TCon Kama will give fleece instead of vanilla wool when a sheep is right clicked?

Thanks!

Reference: https://github.com/Darkosto/SevTech-Ages/issues/504

**Comment by DaedalusGame** [comment]
oh right darkosto mentioned this in dm i have to add a whitelist of shearing implements

**Comment by justinrusso** [comment]
Figured it may have been forgotten :)

**Comment by DaedalusGame** [comment]
~~or so i thought >_>
yeah this will need forge changes or a coremod sorry~~
https://github.com/MinecraftForge/MinecraftForge/issues/4562

actually it appears i've been gone too long and immediently jumped to the bleakest conclusion. I can fix this.
except the fact that scythes are aoe shearing but who cares about that haha

**Comment by DaedalusGame** [comment]
the fix for this is now on curse please report back if this is actually fixed

**Comment by justinrusso** [comment]
So, I thought the AOE would just not work for shearing - but instead it gives the actual wool. We'd be fine with it breaking the AOE for shearing if that's do-able to fix.

**Comment by DaedalusGame** [comment]
It should've done that i just replace the rightclick for the tool

**Comment by justinrusso** [comment]
Well, i thought so too. But I got regular wool from some of the sheep I AOE right clicked

**Comment by DaedalusGame** [comment]
urgh ok i think I'm hooking the wrong event

**Comment by DaedalusGame** [comment]
ok i uploaded a fix (still under review) for the scythe problem and in general it should be a bit more robust with other shear-like items

**Comment by DaedalusGame** [comment]
I assume this is fixed now
