### ISSUE TITLE
Karate Zombie ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by justinrusso** [DaedalusGame/BetterWithAddons#76]
https://gist.github.com/Marioluigi7896/f7d6121b5f6e82166dc3845e3ee443a5

Reference: https://github.com/Darkosto/SevTech-Ages/issues/563

**Comment by DaedalusGame** [comment]
>getting 8 when the max value is 3

GUARDS

**Comment by DaedalusGame** [comment]
ok i have no idea why this happens, probably a deeper seated issue with syncing in multiplayer or loading/saving nbt or datamanagers in general but i will make a patchwork fix

**Comment by DaedalusGame** [comment]
fix for this is on curse
