### ISSUE TITLE
BWA .6 Crash

### ISSUE THREAD

**Issue by sdaddy** [DaedalusGame/BetterWithAddons#8]
A player on my server clicked a nest from the Animania mod and now the server crashes when we try to join. 

Crash log: https://gist.github.com/sdaddy/2e550e59ed8a56bf91156e5439dd5ee6

**Comment by DaedalusGame** [comment]
Okay, I see the problem, EntityItem:getAge exists only on the client, my bad (i wish)
I was gonna add a config in .7 for that handler anyway

**Comment by sdaddy** [comment]
Do you happen to have ETA on an update? I was waiting for a response before either rolling back the server or starting the server without BWA. If you can upload a update/hotfix soon then we can just wait. Thanks for the quick response.

**Comment by DaedalusGame** [comment]
Just need to test it on an actual instance.

**Comment by DaedalusGame** [comment]
It's up
