### ISSUE TITLE
[Bug] [Compatibility] HardcoreShearing, The Enhanced Shears (Ender Sheer) from Cyclic give wool...

### ISSUE THREAD

**Issue by Fireztonez** [DaedalusGame/BetterWithAddons#80]
Hello,
I try with the Cyclic "Enhanced Shears" (cyclicmagic:ender_wool), drop wool block when I Throw to a sheep, and not Fleecy, with HardcoreShearing active. If you can look for fix that it will be amazing!!

Better With Addons: 0.31-hotfix4
Better WIth Mods: 2.0.28
Cyclic: 1.13.6
Forge: 14.23.2.2625

Thank's,
Fireztonez

**Comment by DaedalusGame** [comment]
forge event needed from this point, sorry

**Comment by Fireztonez** [comment]
So, nothing you can do... It's ok, thank's
