### ISSUE TITLE
Lighting Arrow Causes Server Crash

### ISSUE THREAD

**Issue by artdude543** [DaedalusGame/BetterWithAddons#85]
This was reported by a user using the SevTech Pack. The report can be found here: https://pastebin.com/QTR5SAr2

Looks like Client-Side methods trying to be called server side.

Version Used: 0.31hotfix4

**Comment by DaedalusGame** [comment]
ag-ain? it's already supposed to make a firework rocket i will have a look
ah right, the misleading AABB constructor i will have this fixed in no time

**Comment by artdude543** [comment]
Awesome thanks for the quick fix! 😄

**Comment by DaedalusGame** [comment]
I've uploaded the fix to curseforge
