### ISSUE TITLE
Crafting recipe for Writing table recipe not work like show in JEI

### ISSUE THREAD

**Issue by Fireztonez** [DaedalusGame/BetterWithAddons#90]
In JEI, the recipe show for the Writing Table is a table with 8 paper in a single slot (This is sincerely not habitual like recipe... Possibly this is just not possible...).

![image](https://user-images.githubusercontent.com/19277301/38167009-05321052-34fc-11e8-882e-8ebfe689f19b.png)

But when I try to craft the Writing Table I just need 1 paper + 1 table...
![image](https://user-images.githubusercontent.com/19277301/38167023-3dbfbfbe-34fc-11e8-932f-11f99c195cfb.png)

Minecraft: 1.12.2
Better With Addons: 0.34
Better With Mods: 2.0.32
Forge : 14.23.2.2640

**Comment by DaedalusGame** [comment]
there's some odd issue with this i will look into it. Does this happen with just BWA and BWM or are other mods involved? Preferrably not 200 like in sevtech :P

**Comment by Fireztonez** [comment]
For now I just try in my modpack, with only 256 mods #FeelsBadMan

But I can try with less mods for see.

**Comment by Fireztonez** [comment]
With a new pack, where I install only;
- Better With Mod
- Better With Addons
- JEI
- CraftTweaker
- Modtweaker

I get exactly the same result, JEI shows that it takes 8 sheets of paper, but the recipe works with only 1 paper and if I put 64 sheets of paper in the craft table, only one is used for the craft...

**Comment by DaedalusGame** [comment]
oh i think i know whats up lol
