### ISSUE TITLE
Water causing slowness to any entity in it.

### ISSUE THREAD

**Issue by ate0ate** [DaedalusGame/BetterWithAddons#95]
After updating to version .035 I get slowness for a full minute whenever I go in water. It just keeps getting reset to a minute as long as I stay in the water as well. Squids also permanently have it and every other entity that decides to dip their toe in. This issue goes away when downgrading to version .034. This is using the latest forge, v14.23.2.2653. I am also using the WHAT Fluid Fix, if that may be playing a role in things somehow some way.

**Comment by DaedalusGame** [comment]
Oh no. It should've only triggered if you're wearing paper armor. I will check it out.

**Comment by ate0ate** [comment]
Haha, that makes sense. I was wearing Ceramic armor from Rustic if that matters. Probably not since I doubt that squids spawn in paper armor lol. Thanks for looking into things.

**Comment by DaedalusGame** [comment]
Curse always takes longer during this time but a fix is uploaded

**Comment by ate0ate** [comment]
Not a problem. Thanks for the quick fix! Wasn't expecting that. Great mod btw. I remember seeing some of these floating around the old Better than Wolves forum back in the day. Nice to see some of the things that flower killed off make a comeback;)
